Repository projectdiscovery/naabu, pull requests merged in 2021-12, with the labels that each got.

#243 Functional test
  .github/workflows/functional-test.yml
  .gitignore
  v2/cmd/functional-test/main.go
  v2/cmd/functional-test/run.sh
  v2/cmd/functional-test/test-data/request.txt
  v2/cmd/functional-test/testcases.txt
  v2/cmd/internal/testutils/integration.go
Labels: Status: Completed, Type: Enhancement

#244 Adding modules tests + Regression tests
  .github/workflows/build-test.yml
  .github/workflows/codeql-analysis.yml
  v2/go.mod
  v2/pkg/result/results.go
  v2/pkg/result/results_test.go
  v2/pkg/runner/banners_test.go
  v2/pkg/runner/ips_test.go
  v2/pkg/runner/nmap.go
  v2/pkg/runner/nmap_test.go
  v2/pkg/runner/output_test.go
  v2/pkg/runner/ports.go
  v2/pkg/runner/ports_test.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/util.go
  v2/pkg/runner/util_test.go
  v2/pkg/runner/validate.go
  v2/pkg/runner/validate_test.go
  v2/pkg/scan/cdn_test.go
  v2/pkg/scan/connect_test.go
  v2/pkg/scan/externalip_test.go
  v2/pkg/scan/ping_test.go
  v2/pkg/scan/scan_darwin.go
  v2/pkg/scan/tcpsequencer_test.go
Labels: Status: Review Needed, Type: Maintenance

#214 Adding socks5 proxy support
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/scan/option.go
  v2/pkg/scan/scan.go
Labels: Status: Review Needed, Type: Enhancement

#247 Fix for top ports options
  v2/cmd/functional-test/testcases.txt
  v2/pkg/runner/ports.go
  v2/pkg/runner/ports_test.go
Labels: Status: Review Needed, Type: Enhancement

#234 Supports comma separated host scanning
  v2/pkg/runner/targets.go
Labels: Status: Review Needed, Type: Enhancement

#250 support for comma separated hosts
  v2/pkg/runner/options.go
  v2/pkg/runner/targets.go
  v2/pkg/runner/validate.go
  v2/pkg/runner/validate_test.go
Labels: Status: Review Needed, Type: Enhancement
