Repository projectdiscovery/naabu, pull requests merged in 2021-06, with the labels that each got.

#169 deprecating golint
  .github/workflows/build.yaml
  .golangci.yml
  v2/pkg/scan/icmp.go
  v2/pkg/scan/scan.go
Labels: Status: Completed, Type: Maintenance, dependencies

#165 Bugfix misc
  Dockerfile
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/ips.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/targets.go
  v2/pkg/scan/icmp.go
  v2/pkg/scan/option.go
  v2/pkg/scan/scan.go
  v2/pkg/scan/scan_darwin.go
Labels: Type: Bug, Type: Maintenance

#172 Bugfix ipranger
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/targets.go
Labels: Status: Review Needed, bug

#175 Updating release workflow
  .github/workflows/release-binary.yml
  v2/.goreleaser.yml
  v2/.goreleaser/linux.yml
  v2/.goreleaser/mac.yml
  v2/.goreleaser/windows.yml
Labels: bug

#178 Fixing #177
  v2/pkg/runner/runner.go
Labels: bug

#179 Bugfix 177 v2
  v2/go.mod
  v2/go.sum
Labels: Type: Bug

#181 Bugfix misc ipranger
  v2/go.mod
  v2/go.sum
Labels: Type: Bug

#173 v2.0.4
  .github/dependabot.yml
  .github/workflows/build-test.yml
  .github/workflows/build.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dockerhub-push.yml
  .github/workflows/lint-test.yml
  .github/workflows/release-binary.yml
  .github/workflows/release.yml
  .golangci.yml
  .goreleaser.yml
  Dockerfile
  README.md
  v2/.goreleaser/linux.yml
  v2/.goreleaser/mac.yml
  v2/.goreleaser/windows.yml
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/banners.go
  v2/pkg/runner/ips.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/targets.go
  v2/pkg/scan/icmp.go
  v2/pkg/scan/option.go
  v2/pkg/scan/scan.go
  v2/pkg/scan/scan_darwin.go
Labels: Status: Completed
