Repository projectdiscovery/naabu, pull requests merged in 2022-03, with the labels that each got.

#272 stop-resume support
  .github/workflows/lint-test.yml
  v2/cmd/naabu/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/options.go
  v2/pkg/runner/resume.go
  v2/pkg/runner/runner.go
Labels: Status: Review Needed, Type: Enhancement

#285 Updating cdncheck
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/runner.go
  v2/pkg/scan/cdn.go
  v2/pkg/scan/cdn_test.go
Labels: Status: Review Needed, Type: Bug

#282 Stream support
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/targets.go
  v2/pkg/runner/validate.go
  v2/pkg/scan/option.go
  v2/pkg/scan/scan.go
Labels: Type: Enhancement
