Repository projectdiscovery/naabu, pull requests merged in 2022-05, with the labels that each got.

#303 Adding support for passive stream scan
  v2/cmd/functional-test/testcases.txt
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/banners.go
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/validate.go
Labels: Status: Review Needed, Type: Enhancement

#304 Adding nmap ips grouping by range
  v2/cmd/functional-test/testcases.txt
  v2/pkg/runner/nmap.go
  v2/pkg/runner/output_test.go
Labels: Status: Review Needed, Type: Enhancement

#314 added buffer reset
  v2/pkg/runner/runner.go
Labels: Status: Review Needed, Type: Bug

#324 Issue 308 display ip part of cdn
  v2/pkg/runner/options.go
  v2/pkg/runner/output.go
  v2/pkg/runner/output_test.go
  v2/pkg/runner/runner.go
  v2/pkg/scan/option.go
  v2/pkg/scan/scan.go
Labels: Status: Review Needed, Type: Enhancement

#325 Adding temporary check and skip for IPV6 addresses
  v2/pkg/runner/runner.go
  v2/pkg/runner/targets.go
  v2/pkg/runner/targets_test.go
Labels: Status: Review Needed, Type: Bug

#333 Fixing cidr error via networkpolicy upgrade
  v2/go.mod
  v2/go.sum
Labels: Status: Review Needed, Type: Bug

#327 Fixing resume issue condition
  v2/pkg/runner/nmap.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/util.go
Labels: Status: Review Needed, Type: Bug

#335 Added nmap support to passive scan mode
  v2/pkg/runner/runner.go
Labels: Status: Review Needed
