Repository projectdiscovery/naabu, pull requests merged in 2022-06, with the labels that each got.

#328 Adding support for IP6
  .gitignore
  README.md
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/default.go
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/targets.go
  v2/pkg/runner/targets_test.go
  v2/pkg/runner/util.go
  v2/pkg/runner/util_test.go
  v2/pkg/scan/router.go
  v2/pkg/scan/router_darwin.go
  v2/pkg/scan/router_linux.go
  v2/pkg/scan/scan.go
  v2/pkg/scan/scan_unix.go
Labels: Status: Review Needed, Type: Enhancement

#345 Adding source port support via source-ip
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/validate.go
  v2/pkg/scan/scan.go
  v2/pkg/scan/scan_unix.go
Labels: Status: Review Needed, Type: Enhancement

#350 Add health-check
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/healthcheck.go
  v2/pkg/runner/options.go
Labels: Status: Review Needed, Type: Enhancement

#355 Using scanme.sh as functional tests target
  v2/cmd/functional-test/testcases.txt
Labels: Type: Maintenance

#356 End-to-end implementation of socks5 proxy authentication support
  README.md
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/scan/option.go
  v2/pkg/scan/scan.go
Labels: Status: Review Needed, Type: Enhancement

#368 Fix error when config dir does not exists
  v2/pkg/runner/resume.go
Labels: Status: Review Needed, Type: Bug

#346 Adding host discovery
  v2/go.mod
  v2/go.sum
  v2/pkg/result/results.go
  v2/pkg/result/results_test.go
  v2/pkg/runner/banners.go
  v2/pkg/runner/options.go
  v2/pkg/runner/runner.go
  v2/pkg/runner/validate.go
  v2/pkg/scan/arp.go
  v2/pkg/scan/icmp.go
  v2/pkg/scan/ndp.go
  v2/pkg/scan/ping.go
  v2/pkg/scan/scan.go
  v2/pkg/scan/scan_unix.go
Labels: Status: Review Needed, Type: Enhancement

#373 Adding Timeout on stdin read
  v2/go.mod
  v2/go.sum
  v2/pkg/runner/options.go
  v2/pkg/runner/targets.go
Labels: Type: Bug
