Repository projectdiscovery/naabu, pull requests merged in 2023-01, with the labels that each got.

#519 Fixing wrong boolean check on verify condition
  v2/pkg/runner/validate.go
Labels: Type: Bug

#522 Reducing duplicate debug messages on scanned ips
  v2/pkg/runner/runner.go
  v2/pkg/runner/targets.go
Labels: Type: Enhancement

#529 Automatic connect scan with proxy
  v2/pkg/runner/validate.go
Labels: Type: Bug

#534 removed utils folder
  v2/pkg/utils/util.go
Labels: Type: Maintenance

#538 Closing stats on exit
  v2/pkg/runner/runner.go
Labels: Type: Bug
